# Generated by Django 4.2 on 2026-03-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
            ],
        ),
    ]
