# Generated by Django 4.2 on 2026-03-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_category_supplier_user_product_belongto_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('stuff', 'Stuff')], default='customer', max_length=50),
        ),
    ]
