# Generated by Django 4.2 on 2026-03-07 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.user')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='belongto_category',
            unique_together={('category_id', 'product_id')},
        ),
        migrations.CreateModel(
            name='Order_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.product')),
            ],
            options={
                'unique_together': {('order_id', 'order_item_id')},
            },
        ),
    ]
