# Generated by Django 4.2 on 2026-03-07 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_order_alter_belongto_category_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment_Carriers',
            fields=[
                ('carrier_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('shipment_date', models.DateTimeField()),
                ('delivery_date', models.DateTimeField()),
                ('carrier_phone', models.CharField(max_length=20)),
                ('shipment_address', models.CharField(max_length=300)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carrier_partner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.shipment_carriers')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.order')),
                ('warehouse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.product')),
                ('warehouse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.warehouse')),
            ],
        ),
    ]
