# Generated by Django 4.2 on 2026-03-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_shipment_carriers_shipment_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('manager', 'Manager'), ('customer', 'Customer'), ('stuff', 'Stuff')], default='customer', max_length=50),
        ),
    ]
