# Generated by Django 4.2 on 2026-03-25 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_alter_inventory_location_alter_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='name',
        ),
    ]
