# Generated by Django 4.2 on 2026-03-25 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_remove_inventory_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='belongto_category',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='belongto_category',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='warehouse_id',
            new_name='warehouse',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='order_item',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='order_item',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='supplier_id',
            new_name='supplier',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='warehouse_id',
            new_name='warehouse',
        ),
        migrations.AlterUniqueTogether(
            name='belongto_category',
            unique_together={('category', 'product')},
        ),
    ]
