# Generated by Django 4.2 on 2026-03-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_rename_category_id_belongto_category_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
