# Generated by Django 4.2 on 2026-03-26 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_order_status_alter_shipment_carrier_partner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='carrier_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.shipment_carriers'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='carrier_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
