# Generated by Django 4.2 on 2026-04-17 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_alter_product_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
    ]
