# Generated by Django 4.2 on 2026-04-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
