# Generated by Django 4.2 on 2026-04-17 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_shipment_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='shipment',
            name='inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.inventory'),
        ),
    ]
