# Generated by Django 4.2 on 2026-04-17 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_remove_shipment_warehouse_shipment_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.inventory'),
        ),
    ]
